const PEPE_MODELS = [
  "Ninja Mike (1%)",
  "Louis Vuittoad (1%)",
  "Steel Frog (1%)",
  "Gucci Leap (1%)",
  "Raphael (1%)",
  "Toading... (1%)",
  "Leonardo (1%)",
  "Donatello (1%)",
  "Puppy Pug (1%)",
  "Midas Pepe (1%)",
  "Cozy Galaxy (1%)",
  "Fifty Shades (1%)",
  "Magnate (1%)",
  "Emerald Plush (1%)",
  "Stripes (2%)",
  "Sketchy (2%)",
  "Marble (2%)",
  "Christmas (2%)",
  "Bavaria (2%)",
  "Amalgam (2%)",
  "Birmingham (2%)",
  "Red Pepple (2%)",
  "Sunset (2%)",
  "X-Ray (2%)",
  "Frozen (2%)",
  "Princess (2%)",
  "Barcelona (2%)",
  "Yellow Purp (2%)",
  "Santa Pepe (2%)",
  "Emo Boi (2%)",
  "Pink Galaxy (2%)",
  "Milano (2%)",
  "Pepe La Rana (2%)",
  "Pink Latex (2%)",
  "Two Face (2%)",
  "Kung Fu Pepe (2%)",
  "Red Menace (3%)",
  "Polka Dots (3%)",
  "Pumpkin (3%)",
  "Yellow Hug (3%)",
  "Hothead (3%)",
  "Tropical (3%)",
  "Eggplant (3%)",
  "Aqua Plush (3%)",
  "Pepemint (3%)",
  "Gummy Frog (3%)",
  "Spectrum (3%)",
  "Cold Heart (3%)",
  "Poison Dart (3%)",
  "Hue Jester (3%)",
];
const MINIOSCAR = [
  "Boulevard (0.5%)",
  "Producer (0.5%)",
  "Solid Bronze (0.5%)",
  "Fiery-Hot (0.5%)",
  "Nightmare (0.5%)",
  "Nebula (0.5%)",
  "Silver Zebra (0.5%)",
  "Sunset Idol (0.5%)",
  "Red Carpet (0.5%)",
  "Makeup (0.5%)",
  "Grape Cola (0.5%)",
  "Trailer (0.5%)",
  "Golden Sky (0.5%)",
  "Violet (0.5%)",
  "Patina (0.5%)",
  "Cold Feet (0.5%)",
  "Hot Shots (0.5%)",
  "Fading Flare (0.5%)",
  "Zesty (0.5%)",
  "Nominee (0.5%)",
  "Silver Screen (0.5%)",
  "Blue Lagoon (0.5%)",
  "Emerald (0.5%)",
  "Regent (0.5%)",
  "Grenadine (0.5%)",
  "Radioactive (0.5%)",
  "Blue Sky (0.5%)",
  "Jokester (0.5%)",
  "Sour Gummy (0.5%)",
  "Starlight (0.5%)",
  "Prestige (0.5%)",
  "Giraffe (0.5%)",
  "Hobgoblin (0.5%)",
  "Spirulina (0.5%)",
  "Red Dream (0.5%)",
  "Cobalt (0.5%)",
  "Premiere (0.5%)",
  "Obsidian (0.5%)",
  "Woody Allen (0.5%)",
  "Leopard (0.5%)",
  "Neon Police (0.5%)",
  "Molten Gold (0.5%)",
  "Mango Tango (0.5%)",
  "Banana (0.5%)",
  "Pumpkin (1%)",
  "Finest Fish (1%)",
  "Amanita (1%)",
  "Ballerino (1%)",
  "Martian (1%)",
  "Gas Mask (1%)",
  "Khajiit (1%)",
  "Brain Slug (1%)",
  "Catwoman (1%)",
  "Android (1%)",
  "Rear End (1%)",
  "Skeleton (1%)",
  "Mars Attacks (1%)",
  "Stuntman (1%)",
  "Moai Figure (1%)",
  "Eye Candy (1%)",
  "Blockbuster (1%)",
  "Flexible (1.5%)",
  "Golfer (1.5%)",
  "Robocop (1.5%)",
  "Crusader (1.5%)",
  "Undead (1.5%)",
  "Poseidon (1.5%)",
  "Dark Knight (1.5%)",
  "Pigeon (1.5%)",
  "Mummy (1.5%)",
  "Aztec God (1.5%)",
  "Caveman (1.5%)",
  "Dark Side (1.5%)",
  "Pink Guard (1.5%)",
  "Speaker (1.5%)",
  "Viking (1.5%)",
  "Static (1.5%)",
  "Chieftain (1.5%)",
  "Santa Claus (1.5%)",
  "Pharaoh (1.5%)",
  "Best Comedy (1.5%)",
  "Legionary (1.5%)",
  "Sprunki (1.5%)",
  "Seraphim (1.5%)",
  "Scream (1.5%)",
  "Cyclopes (1.5%)",
  "Welder (1.5%)",
  "Spidey (1.5%)",
  "Pirate (1.5%)",
  "Brainiac (1.5%)",
  "Astronaut (1.5%)",
  "Main Villain (1.5%)",
  "The Deep (1.5%)",
  "Dracula (1.5%)",
  "Tribal Idol (1.5%)",
  "Deep Freeze (2%)",
  "Action Film (2%)",
  "Laser Scan (2%)",
  "Electric (2%)",
  "Christmas (2%)",
];
const TOYBEARS = [
  "Golden Cub (0.4%)",
  "Diamond (0.5%)",
  "Dark Knight (0.5%)",
  "Deadpool (0.5%)",
  "Ursa Major (0.5%)",
  "Blueprint (0.5%)",
  "Lunaris (0.5%)",
  "Matrix (0.5%)",
  "Copper (0.8%)",
  "Lapis Lazuli (0.8%)",
  "Wall Street (0.8%)",
  "Chocolate (0.8%)",
  "Dragon Ruby (0.8%)",
  "Fazbear (1%)",
  "Pooh (1%)",
  "Kumamon (1%)",
  "Angel (1%)",
  "Rilakkuma (1%)",
  "The Devil (1%)",
  "Tiger (1%)",
  "Winnie (1%)",
  "Teddy-800 (1.2%)",
  "Bumblebear (1.2%)",
  "Checkmate (1.2%)",
  "Bearly Visible (1.2%)",
  "Alter Ego (1.3%)",
  "Cuddle (1.3%)",
  "Little Pepe (1.3%)",
  "Tricolor (1.3%)",
  "Pajamas (1.5%)",
  "Matroskin (1.5%)",
  "Panda (1.5%)",
  "Los Muertos (1.5%)",
  "Cowboy (1.5%)",
  "Cozy Boy (1.5%)",
  "Contractor (1.5%)",
  "Panda Cow (1.5%)",
  "Toady Bear (1.5%)",
  "Tuxedo (1.5%)",
  "Color Switch (1.5%)",
  "Graduate (1.5%)",
  "Macchiato (1.5%)",
  "Wizard (1.5%)",
  "Froggo (1.5%)",
  "Snowman (1.5%)",
  "Zebra (1.5%)",
  "Polygon (1.5%)",
  "Watermelon (1.5%)",
  "Nurse (1.8%)",
  "Polar Bear (2%)",
  "Night Cub (2%)",
  "Cotton (2%)",
  "Citrus (2%)",
  "Viola Pansy (2%)",
  "Noir Et Rose (2%)",
  "Pink Doodle (2%)",
  "Blueberry (2%)",
  "Purple Heart (2%)",
  "El Rojo (2%)",
  "Skittles (2%)",
  "Circus Bear (2%)",
  "Coral Reef (2.2%)",
  "Cherry (2.2%)",
  "Malibu (2.2%)",
  "Pineapple (2.2%)",
  "Red Velvet (2.2%)",
  "Blue Dandy (2.2%)",
  "Pink Cactus (2.2%)",
  "Carrot (2.2%)",
  "Peanut (2.2%)",
];
const LOOTBAG = [
  "Woof Pack (0.5%)",
  "Scrooge (0.5%)",
  "Black Purrse (0.5%)",
  "Glacier (0.5%)",
  "Panthera (0.5%)",
  "Miranda (0.5%)",
  "Priestly (0.5%)",
  "Fluorescent (0.5%)",
  "Lust Beat (0.5%)",
  "Circus (0.5%)",
  "Pendragon (0.5%)",
  "Money Bag (0.5%)",
  "Crypto Punk (0.5%)",
  "Conductor (0.5%)",
  "Instabag (0.5%)",
  "Bouquet (0.5%)",
  "City Life (0.5%)",
  "Nightmare (0.5%)",
  "Secret Toys (0.5%)",
  "Crypto Byte (0.5%)",
  "Riot Pack (0.5%)",
  "Poison Dart (0.5%)",
  "Liberty (0.5%)",
  "Pepe Bag (0.5%)",
  "Ardente (0.5%)",
  "Travel Bag (0.5%)",
  "Contour (1%)",
  "Metro Trench (1%)",
  "Dark Arches (1%)",
  "Pink Pulsar (1%)",
  "Faubourg (1%)",
  "Night City (1%)",
  "Highway (1%)",
  "Boulevard (1%)",
  "Road Trip (1%)",
  "Sunset Stripes (1.5%)",
  "Courchevel (1.5%)",
  "Satin Beige (1.5%)",
  "White Pony (1.5%)",
  "Jade Serpent (1.5%)",
  "Verso Blue (1.5%)",
  "Grizzly (1.5%)",
  "Rose Tyrien (1.5%)",
  "Steel Agate (1.5%)",
  "Jaune Poussin (1.5%)",
  "Biscuit (1.5%)",
  "Tropical (1.5%)",
  "Sunrise Bands (1.5%)",
  "Aero Swift (1.5%)",
  "Orange Croc (1.5%)",
  "Reptile Noir (1.5%)",
  "Menthol (1.5%)",
  "Aqua Atoll (1.5%)",
  "Vert d'Eau (1.5%)",
  "Soft Suede (1.5%)",
  "Cherry Croc (1.5%)",
  "Anemone (1.5%)",
  "Silver Gator (1.5%)",
  "Rouge Royale (1.5%)",
  "Academic (2%)",
  "Burgun Bag (2%)",
  "Riviera (2%)",
  "Jaune Citrone (2%)",
  "Cherry Red (2%)",
  "Potamus (2%)",
  "Ombre (2%)",
  "Argylle (2%)",
  "Matte Mint (2%)",
  "Sakura (2%)",
  "Vertigo (2%)",
  "Cargo Citron (2%)",
  "Zip Pocket (2%)",
  "Bleu Officier (2%)",
  "Studded Green (2%)",
  "Black Ascot (2%)",
  "Tressage (2%)",
  "Tangerine (2%)",
  "Racing Stripes (2%)",
  "Cortado (2%)",
  "Chrome Clutch (2%)",
];
const DUROVSHAT = [
  "Asterix (0.5%)",
  "RGB Glitch (1%)",
  "Artwork (1%)",
  "Cartoon (1.5%)",
  "Fun Time (1.5%)",
  "Honey Bee (1.5%)",
  "Snowfall (1.5%)",
  "Captain (1.5%)",
  "Cotton Candy (1.5%)",
  "Falcon (1.5%)",
  "Toxic Guy (1.5%)",
  "Neon (1.5%)",
  "Voltage (1.5%)",
  "Tron (1.5%)",
  "Jetspin (1.5%)",
  "Redrum (1.5%)",
  "Frosted Brew (2%)",
  "Bog Moss (2%)",
  "Duck Tales (2%)",
  "Krueger (2%)",
  "Sunrise (2%)",
  "Autumn (2%)",
  "Sea Sunset (2%)",
  "Corkwood (2%)",
  "Dipper (2%)",
  "Seabreeze (2%)",
  "Nightshade (2%)",
  "Apple Slice (2%)",
  "Chicago Bulls (2%)",
  "Freshwave (2%)",
  "Pink Pop (2%)",
  "Ashen (2%)",
  "Goldrose (2%)",
  "Night Ivy (2%)",
  "Negative (2%)",
  "Shadeux (2%)",
  "Creamsicle (2%)",
  "Bluebird (2%)",
  "Shadow (2%)",
  "Ivory (2%)",
  "Pinkie Cap (2%)",
  "Villager (2%)",
  "Aurora (2%)",
  "Sky High (2%)",
  "Sepium (2%)",
  "Mossy (2%)",
  "Patriot (2%)",
  "Jade (2%)",
  "Macintosh (2%)",
  "Duskwave (2%)",
  "Bordeaux (2%)",
  "Pokemon (2%)",
  "Classic (2%)",
  "Frosthorn (2%)",
  "Candy Shade (2%)",
];
const SCAREDCAT = [
  "Bubblegum (0.5%)",
  "Garfield (0.5%)",
  "Misty Ash (0.5%)",
  "Fern (0.5%)",
  "Mentos (0.5%)",
  "Azuki Siam (0.5%)",
  "Salem (1%)",
  "Oreo (1%)",
  "Caramel (1%)",
  "Jaddy (1%)",
  "Vampkitty (1%)",
  "Cat2O (1%)",
  "Purrrple (1%)",
  "Vice Kitty (1%)",
  "Cake (1%)",
  "Chili Whisk (1%)",
  "Cookie (1%)",
  "Yolkster (1%)",
  "Blitzo (1.5%)",
  "Gecko Cat (1.5%)",
  "Goodbye Kitty (1.5%)",
  "El Tigre (1.5%)",
  "Bipolar Cat (1.5%)",
  "Jeopard (1.5%)",
  "Ruby (1.5%)",
  "Copperclaw (1.5%)",
  "Ranni (1.5%)",
  "Phantom (1.5%)",
  "Silver Napper (2%)",
  "Obelisk (2%)",
  "Meowdas (2.5%)",
  "Nebula (2.5%)",
  "Niko (2.5%)",
  "Esmeralda (2.5%)",
  "Caustic (3%)",
  "Celestia (3%)",
  "Endercat (3%)",
  "Pepe Paws (3%)",
  "Cathulhu (3%)",
  "Creeper (3.5%)",
  "Instacat (3.5%)",
  "Purrlion (3.5%)",
  "Nyan Cat (3.5%)",
  "Torracat (3.5%)",
  "Weedcat (3.5%)",
  "Voodoo (4%)",
  "Cat Nukem (4%)",
  "Virus (4%)",
  "Puss in Boots (4%)",
  "Vapurr (4%)",
];
const DIAMONDRING = [
  "Graffiti (0.5%)",
  "Ocean Gem (0.5%)",
  "Firestorm (0.5%)",
  "Royal Purple (0.5%)",
  "Bubble Burst (0.5%)",
  "Line Art (0.5%)",
  "Midnight (0.5%)",
  "Freehand (0.5%)",
  "Pink Diamond (0.5%)",
  "Silver Star (0.5%)",
  "Doodle (0.5%)",
  "Valentine (0.5%)",
  "Cold Desire (0.5%)",
  "Nocturne (0.5%)",
  "Sketch (0.5%)",
  "Blood Orange (0.5%)",
  "Bloodstone (0.5%)",
  "Iron Feather (0.5%)",
  "Marigold (0.5%)",
  "Snake Eye (0.5%)",
  "Black Hole (0.5%)",
  "Color Blocks (0.5%)",
  "Color Spray (0.5%)",
  "Ocean Agate (0.5%)",
  "Obsidian (0.5%)",
  "Fireball (0.5%)",
  "Manhattan (0.5%)",
  "Whirlpool (0.5%)",
  "Pure Love (0.5%)",
  "Sapphire (0.5%)",
  "Rainbow (0.5%)",
  "Diamond (0.5%)",
  "Tesla (0.5%)",
  "Goldfinger (0.5%)",
  "Silver Smoke (0.5%)",
  "Black Thorn (0.5%)",
  "Cold Fusion (0.5%)",
  "Cobalt Rose (0.5%)",
  "Inferno (0.5%)",
  "Vice City (0.5%)",
  "Blood Band (0.5%)",
  "Orion (0.5%)",
  "Velvet Rose (0.5%)",
  "Couture (0.5%)",
  "Pink Lover (0.5%)",
  "Frostband (0.5%)",
  "Red Velvet (0.5%)",
  "El Dorado (1%)",
  "Steampunk (1%)",
  "Silver Lake (1%)",
  "Sunset (1%)",
  "Twilight (1%)",
  "Eclipse (1%)",
  "Aurora (1.5%)",
  "Acid Green (1.5%)",
  "Water Lily (1.5%)",
  "Dark Orchid (1.5%)",
  "Champagne (1.5%)",
  "Red Wedding (1.5%)",
  "Canary (1.5%)",
  "Black Velvet (1.5%)",
  "Miami Beach (1.5%)",
  "Color Chaos (1.5%)",
  "Red Light (1.5%)",
  "Citrus Shift (1.5%)",
  "Forest Lake (1.5%)",
  "Quick Silver (1.5%)",
  "Hot Pink (1.5%)",
  "Emerald (1.5%)",
  "Topaz (1.5%)",
  "Sunrise (1.5%)",
  "Barbie Gem (1.5%)",
  "Arabian Night (1.5%)",
  "Vintage Glam (1.5%)",
  "Honeydew (1.5%)",
  "Rose Quartz (1.5%)",
  "Azurite (1.5%)",
  "Space Steel (1.5%)",
  "Bondi Blue (1.5%)",
  "Mikado Yellow (1.5%)",
  "Mint Candy (1.5%)",
  "Dragon Eyes (1.5%)",
  "Bronze Heart (1.5%)",
  "Scrapyard (1.5%)",
  "Prismatic (1.5%)",
  "Peridot (1.5%)",
  "Black Amber (1.5%)",
  "Ultramarine (1.5%)",
  "Blue Pearl (1.5%)",
  "Flamingo (1.5%)",
  "Nightshade (1.5%)",
  "Amethyst (1.5%)",
  "Dorodango (1.5%)",
  "Elven Tears (1.5%)",
  "Copper Rose (1.5%)",
  "Clam Shell (1.5%)",
  "Princess Cut (1.5%)",
  "Glamour (1.5%)",
  "Neon Chrome (1.5%)",
  "Sovereign (1.5%)",
];
const GINGER = [
  "Universe (0.1%)",
  "Sugar Star (0.2%)",
  "Telegram (0.2%)",
  "Frostbite (0.2%)",
  "Tied Up (0.2%)",
  "Brand New (0.2%)",
  "Pika Pika (0.2%)",
  "Golden Boy (0.2%)",
  "Hello Cookie (0.2%)",
  "Rose Gold (0.2%)",
  "Pun-Cake (0.2%)",
  "White Gold (0.2%)",
  "Platinum (0.2%)",
  "Cookie Claus (0.3%)",
  "Headless (0.3%)",
  "Shortbread (0.3%)",
  "Sprinkles (0.3%)",
  "Paprika (0.3%)",
  "Beach Party (0.3%)",
  "Dracula (0.3%)",
  "Lebkuchen (0.6%)",
  "Eve (0.6%)",
  "Galleta (0.6%)",
  "Bronze (0.6%)",
  "Black Beard (0.6%)",
  "Bone Appétit (0.6%)",
  "Cop Cake (0.6%)",
  "Adam (0.6%)",
  "Pepe Pryanik (0.6%)",
  "Jolly Roger (0.6%)",
  "Shanker (0.6%)",
  "Le Biscuit (0.6%)",
  "Silver (0.6%)",
  "Amaretto (0.6%)",
  "Santa Claus (0.7%)",
  "Candy Cane (0.7%)",
  "Berry Button (0.7%)",
  "Crunched (0.7%)",
  "Coffee Break (0.7%)",
  "Hazel Bezel (0.7%)",
  "Ginger Geek (0.7%)",
  "Melonius (0.7%)",
  "Reel Cookie (0.8%)",
  "Red Scarf (0.8%)",
  "Herb Garden (0.8%)",
  "Dandy Candy (0.9%)",
  "Lil Ginger (0.9%)",
  "Choco Swirl (0.9%)",
  "Bavarian (0.9%)",
  "Sweetheart (0.9%)",
  "Mint Fringe (0.9%)",
  "Cooking... (1.1%)",
  "Pink Molasses (1.2%)",
  "Bio Glow (1.2%)",
  "Toblerone (1.2%)",
  "Madagascar (1.2%)",
  "Choco Glazed (1.2%)",
  "Brownie (1.2%)",
  "Raspberry (1.2%)",
  "Royal Sundae (1.2%)",
  "Unicorn (1.2%)",
  "Cocoa Powder (1.2%)",
  "Red Velvet (1.2%)",
  "Dark Almond (1.2%)",
  "Eskimo (1.3%)",
  "Matrix (1.4%)",
  "Opposite (1.5%)",
  "Faint Blush (1.5%)",
  "Waffle (1.5%)",
  "Glowberry (1.5%)",
  "Frosty (1.5%)",
  "Marshmallow (1.5%)",
  "Template (1.5%)",
  "Johnny Ash (1.5%)",
  "Icing Sugar (1.6%)",
  "Banana Bread (1.6%)",
  "Gentleman (1.6%)",
  "Moon Dust (1.6%)",
  "Champagne (1.6%)",
  "Frozen Dough (1.6%)",
  "Cardamom (1.6%)",
  "Periwinkle (1.6%)",
  "Hulking (1.7%)",
  "Ginger Grape (1.7%)",
  "Marzipan (1.7%)",
  "Truffle (1.7%)",
  "Mr. Biscuit (1.7%)",
  "Ice Latte (1.7%)",
  "Toffee (1.7%)",
  "Candy Bar (1.7%)",
  "Vanilla (1.7%)",
  "Cinnamon (1.7%)",
  "Snowman (1.7%)",
  "Cheesecake (1.7%)",
  "Pistachio (1.7%)",
  "Rubber Duck (1.7%)",
  "Strawberry (1.7%)",
  "Bordeaux (1.7%)",
  "Sunspot (1.7%)",
  "Rose Water (1.7%)",
];
const SIGNETRING = [
  "Skibidi (0.3%)",
  "Crypto Boom (0.8%)",
  "Carpenter (1%)",
  "Black Noir (1%)",
  "Dirt Diamond (1%)",
  "Mood Ring (1%)",
  "Saturn Ring (1%)",
  "Ice Queen (1%)",
  "Ring of Power (1%)",
  "Off-Axis (1%)",
  "Skull (1%)",
  "Kitteh (1%)",
  "Good Boy (1%)",
  "Tony Stark (1%)",
  "Nyan Cat (1.2%)",
  "Symbolic (1.5%)",
  "Star Platinum (1.5%)",
  "Utya (1.5%)",
  "Silverscreen (1.5%)",
  "Diamonds (2%)",
  "Christmas (2%)",
  "Clubs (2%)",
  "Sakura Gold (2%)",
  "Emerald (2%)",
  "TON (2%)",
  "Spades (2%)",
  "Candy Cane (2%)",
  "Titanium (2%)",
  "Obsidian (2%)",
  "Hearts (2%)",
  "Liberty (2%)",
  "Citrine (2%)",
  "Chrome (2%)",
  "Sapphire (2%)",
  "Mandarin (2%)",
  "Green Lantern (2%)",
  "Pristine (2%)",
  "Yin-Yang (2.5%)",
  "Blue Gold (3%)",
  "Jade Lord (3%)",
  "Blued Steel (3%)",
  "Black Opal (3%)",
  "Little Star (3%)",
  "Onyx Demon (3%)",
  "Green Rose (3.2%)",
  "Platinum (4%)",
  "Rose Gold (4%)",
  "Gold (4%)",
  "Golden Pearl (4%)",
  "White Gold (4%)",
];
const VINTAGECIGAR = [
  "Spectral Smoke (0.3%)",
  "The Shocker (0.3%)",
  "Saturn V (0.3%)",
  "Short Fuse (0.3%)",
  "El Classico (0.3%)",
  "Ice Cold (0.3%)",
  "Super Swirls (0.3%)",
  "Far Out (0.4%)",
  "Psychonaut (0.5%)",
  "Oil Baron (0.5%)",
  "Pink Plume (0.5%)",
  "Jazz Cigarette (0.5%)",
  "The Gentleman (1%)",
  "Silver Fox (1%)",
  "Rainbow Road (1%)",
  "Centurion (1%)",
  "Ashtray (1%)",
  "Dark Clouds (1%)",
  "Thermal (1%)",
  "Gray Matter (1%)",
  "High Tide (1.5%)",
  "Pink Panther (2%)",
  "Black Plume (2%)",
  "Pearl Puff (2%)",
  "Green Goblin (2%)",
  "Mellow Yellow (2%)",
  "Green Gas (2%)",
  "Cobalt (2%)",
  "Seeing Red (2%)",
  "Sunset Orange (2%)",
  "Warm Glow (2%)",
  "Silver Bullet (2%)",
  "Foundry (2%)",
  "Pickle Rick (2%)",
  "Purple Haze (2%)",
  "Long Draw (2%)",
  "Golden Hour (2%)",
  "Secret Santa (2%)",
  "Cool Blue (2%)",
  "Blue Hue (3%)",
  "Desert Night (3%)",
  "Saturation (3%)",
  "Blue Ghoul (3%)",
  "Aquaviolet (3%)",
  "Pink Ghost (3%)",
  "Mirror Finish (3%)",
  "Rudolph (3%)",
  "Stained Glass (3%)",
  "Purple Patron (3%)",
  "Rose Wrapper (3%)",
  "Vaporwave (3%)",
  "Subtle Purple (3%)",
  "Pink Tint (3%)",
  "Premium Blend (4%)",
  "Red Devil (4%)",
];
const SWISSWATCH = [
  "Dr. Strange (1.5%)",
  "DeLorean (1.5%)",
  "The Grid (1.5%)",
  "Secret Agent (1.5%)",
  "Future Watch (1.5%)",
  "Day Trader (1.5%)",
  "Iced Out (1.5%)",
  "Pot of Gold (1.5%)",
  "Pink Cycle (1.5%)",
  "Spacewalk (1.5%)",
  "Salvador (1.5%)",
  "Memory Flash (1.5%)",
  "Intergalactic (1.5%)",
  "Sputnik (1.5%)",
  "Cherry Time (1.5%)",
  "Asteroid (1.5%)",
  "Sean Connery (1.5%)",
  "Cupid Clock (1.5%)",
  "Xenowatch (1.5%)",
  "Galactic Year (2%)",
  "Platinum (2%)",
  "Copper Clock (2%)",
  "Timeless (2%)",
  "Sovereign (2%)",
  "Infinite Loop (2%)",
  "Bruce Wayne (2%)",
  "Ball Pit (2%)",
  "El Dorado (2%)",
  "Chromatic (2%)",
  "Outer Space (2%)",
  "Top Gun (2%)",
  "Inception (2%)",
  "Rockefeller (2%)",
  "Patriot (2%)",
  "Helicopter (2%)",
  "Bronze Age (2.5%)",
  "Full Tint (2.5%)",
  "Day-Date (2.5%)",
  "Pip-Boy (2.5%)",
  "Amazon (2.5%)",
  "Zenith (2.5%)",
  "Blue Daytona (2.5%)",
  "Diamond Ring (2.5%)",
  "Patrician (2.5%)",
  "Gameboy (2.5%)",
  "Tachymeter (2.5%)",
  "Royal Purple (3%)",
  "Gold Band (3%)",
  "The Original (3%)",
  "Blue Bezel (3%)",
];

const MODELS = {
  "Mini Oscar_MODELS": MINIOSCAR,
  "Scared Cat_MODELS": SCAREDCAT,
  "Signet Ring_MODELS": SIGNETRING,
  "Swiss Watch_MODELS": SWISSWATCH,
  "Vintage Cigar_MODELS": VINTAGECIGAR,
  "Durov's Cap_MODELS": DUROVSHAT,
  "Plush Pepe_MODELS": PEPE_MODELS,
  "Diamond Ring_MODELS": DIAMONDRING,
  "Ginger Cookie_MODELS": GINGER,
  "Loot Bag_MODELS": LOOTBAG,
  "Toy Bear_MODELS": TOYBEARS,
};

module.exports = MODELS;
